CREATE TABLE [dbo].[Period]
(
	[Id] BIGINT NOT NULL PRIMARY KEY,
    [PriceEpisodeId] BIGINT NOT NULL CONSTRAINT FK__Period_PriceEpisode FOREIGN KEY REFERENCES [dbo].[PriceEpisode] (Id),
    [Period] INT NOT NULL, 
    [IsPayable] BIT NOT NULL, 
    [AccountId] BIGINT NULL, 
    [ApprenticeshipId] BIGINT NULL, 
    [ApprenticeshipEmployerType] INT NULL, 
    [TransferSenderAccountId] BIGINT NOT NULL, 
    [FailedDataLock1] BIT NOT NULL DEFAULT 0,
    [FailedDataLock2] BIT NOT NULL DEFAULT 0,
    [FailedDataLock3] BIT NOT NULL DEFAULT 0,
    [FailedDataLock4] BIT NOT NULL DEFAULT 0,
    [FailedDataLock5] BIT NOT NULL DEFAULT 0,
    [FailedDataLock6] BIT NOT NULL DEFAULT 0,
    [FailedDataLock7] BIT NOT NULL DEFAULT 0,
    [FailedDataLock8] BIT NOT NULL DEFAULT 0,
    [FailedDataLock9] BIT NOT NULL DEFAULT 0,
    [FailedDataLock10] BIT NOT NULL DEFAULT 0,
    [FailedDataLock11] BIT NOT NULL DEFAULT 0,
    [FailedDataLock12] BIT NOT NULL DEFAULT 0,
    [Amount] DECIMAL(15, 5) NOT NULL, 
    [TransactionType] INT NOT NULL,
    [CreationDate]  DATETIMEOFFSET NOT NULL CONSTRAINT DF_Period__CreationDate DEFAULT (SYSDATETIMEOFFSET()), 
)
