trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
  clean: all
  
variables:
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'
- group: 'Prod Management Resources'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency

pool:
  name: 'DAS - Continuous Integration Agents'
  demands: LATEST_DOTNET_VERSION -equals 3.1

steps:
- template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

- template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

- template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SFA.DAS.Payments.MatchedLearner.Api/SFA.DAS.Payments.MatchedLearner.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    contents: |
      azure/**
    targetFolder: '$(build.artifactstagingdirectory)/publish'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(build.artifactstagingdirectory)/publish'
