trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/DASD-8904-ConditionalAcceptanceTests
    endpoint: 'GitHub (SFA)'

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: pipeline-templates/job/dacpac-build.yml