trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.37
    endpoint: SkillsFundingAgency

variables:
  - name: SolutionBaseName
    value: SFA.DAS.Payments.MatchedLearner.Api

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)