trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
  clean: all
  
variables:
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'
- group: 'Prod Management Resources'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.1
    endpoint: 'GitHub (SFA)'

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
#  - template: pipeline-templates/job/dacpac-build.yml